### PR TITLE
Merged in latest development from the mainline repo + fixed build issues

### PR DESCRIPTION
**Pull request by anton-matosov**

### CODE REVIEW

**Comment by markst** [comment]
@anton-matosov nice one. might be good to do this again with the latest https://github.com/RestKit/RestKit/commit/7a5b7e832c44222c3f8a1f1f6546263baf816f88 ?

**Comment by markst** [comment]
since there now seems to be builds issue when using CocoaPods `0.39`

**Comment by oligriffiths** [comment]
Did this not touch any of my code changes?

**Comment by anton-matosov** [comment]
As far as I understand - no

**Comment by ilyakaz** [comment]
@anton-matosov Hi there. It looks like you guys are working on factoring out AFNetworking and replacing it with ipv6 compliant behavior. We are heavily invested in RestKit and I am very interested in your work. What's available now seems to be doing the job for us except I can't find a replacement for the code we use to retrieve image binaries. We did it with the help of AFNetworking 1.x's AFImageRequestOperation operation. I know that in AFNetworking 2.x the same functionality can be achieved with something like this:

RKHTTPRequestOperation *requestOperation = ... initialization code ...;
requestOperation.responseSerializer = [AFImageResponseSerializer serializer];

Do you know if anyone's working on this?

**Comment by wainglaister** [comment]
Hi, been absent for a while :-) There's a cocoa pods merge pending on the main line (https://github.com/RestKit/RestKit/pull/2310) that we should look at and then talk about merging this back to the mainline

**Comment by oligriffiths** [comment]
Agreed. 

My progress has been pretty slow. We need to work out if we're supporting miltipart upload for the initial release or not. And sort out tests.

**Comment by wainglaister** [comment]
Hopefully i have time to look at the tests going forwards. Initial look shows there are a few holes to patch up, which isn't unexpected after such a big change. I'll let you know how I get on, but it won't be for a week or 2 I'm afraid.

It would be good to get a multipart solution in too, there should be tests for that and I'd rather not take them out :)

**Comment by markst** [comment]
hey guys. are there any developments on this?

**Comment by ptclarke** [comment]
Did some testing a few months back will try and get back to it next week and send through feedback.

**Pull request closed without merging**
